name: so-halal

services:
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: "postgres:latest"
    container_name: postgres
    environment:
      POSTGRES_DB: halal_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./postgres/scripts:/docker-entrypoint-initdb.d/ 

volumes:
  postgres:
